-- Optic Manager V3
-- Exécuter /api/setup après déploiement.

CREATE TABLE IF NOT EXISTS sales (
  id SERIAL PRIMARY KEY,
  sale_number TEXT UNIQUE,
  sale_date DATE DEFAULT CURRENT_DATE,
  status TEXT DEFAULT 'brouillon',
  agency_name TEXT NOT NULL,
  seller_email TEXT,
  client_name TEXT NOT NULL,
  client_phone TEXT,
  client_age INTEGER,
  client_gender TEXT,
  client_address TEXT,
  product_type TEXT NOT NULL,
  frame_brand TEXT,
  frame_reference TEXT,
  lens_type TEXT,
  payment_method TEXT,
  total_amount NUMERIC NOT NULL DEFAULT 0,
  paid_amount NUMERIC DEFAULT 0,
  is_insured BOOLEAN DEFAULT FALSE,
  insurance_company TEXT,
  insurance_number TEXT,
  insurance_rate NUMERIC DEFAULT 0,
  insurance_amount NUMERIC DEFAULT 0,
  prescription_file_name TEXT,
  prescription_file_type TEXT,
  prescription_file_data TEXT,
  follow_up_date DATE,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
